{
  "formatVersion": "1.1",
  "component": {
    "group": "WanAndroid",
    "module": "plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-unspecified.jar",
          "url": "plugin-unspecified.jar",
          "size": 6357,
          "sha512": "b06dafbdcd0608d717957dda4a72854ee3d5fcc3f28c693fa2d0be42ef0528007a585cb7f526d706e3e0b8acde7b4609cd0411d13ff16acfd234513c802b7bc8",
          "sha256": "6db13ad4fb37914e6a53c8db518a7b09ac3f21d5617df44f8cfe4a6ab5bb6a62",
          "sha1": "642986681ac52d8dbbd572739cc8767006acac09",
          "md5": "bfe37e5cc2b9e88932a55da5dabb9127"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-unspecified.jar",
          "url": "plugin-unspecified.jar",
          "size": 6357,
          "sha512": "b06dafbdcd0608d717957dda4a72854ee3d5fcc3f28c693fa2d0be42ef0528007a585cb7f526d706e3e0b8acde7b4609cd0411d13ff16acfd234513c802b7bc8",
          "sha256": "6db13ad4fb37914e6a53c8db518a7b09ac3f21d5617df44f8cfe4a6ab5bb6a62",
          "sha1": "642986681ac52d8dbbd572739cc8767006acac09",
          "md5": "bfe37e5cc2b9e88932a55da5dabb9127"
        }
      ]
    }
  ]
}
